javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" core/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" movement/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" report/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" routing/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" gui/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" input/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" applications/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" interfaces/*.java
javac -cp ".;lib/ECLA.jar;lib/DTNConsoleConnection.jar" trust/*.java
